version: 0.2

# Test buildspec for running application tests

env:
  variables:
    ENVIRONMENT: "dev"
    TEST_RESULTS_DIR: "test-results"
    COVERAGE_DIR: "coverage"

phases:
  install:
    commands:
      - echo "Installing test dependencies..."
      - |
        if [ -f package.json ]; then
          # Node.js application
          npm install
        elif [ -f requirements.txt ]; then
          # Python application
          pip install -r requirements.txt
        fi
      
  pre_build:
    commands:
      - echo "Pre-test setup..."
      - echo "Test environment = $ENVIRONMENT"
      - mkdir -p $TEST_RESULTS_DIR
      - mkdir -p $COVERAGE_DIR

  build:
    commands:
      - echo "Running tests..."
      
      # HTML Validation Tests
      - echo "Validating HTML structure..."
      - |
        HTML_FILE="app/index.html"  
        
        if [ -f "$HTML_FILE" ]; then
          echo "✓ $HTML_FILE exists"
          
          # Check for required elements
          grep -q "<html" "$HTML_FILE" && echo "✓ HTML tag found" || (echo "✗ HTML tag missing" && exit 1)
          grep -q "<head" "$HTML_FILE" && echo "✓ Head tag found" || (echo "✗ Head tag missing" && exit 1)
          grep -q "<body" "$HTML_FILE" && echo "✓ Body tag found" || (echo "✗ Body tag missing" && exit 1)
          grep -q "<title" "$HTML_FILE" && echo "✓ Title tag found" || (echo "✗ Title tag missing" && exit 1)
          
          # Check for deployment info
          grep -q "Deployment" "$HTML_FILE" && echo "✓ Deployment text found" || (echo "✗ Deployment text missing" && exit 1)
          grep -q "Version" "$HTML_FILE" && echo "✓ Version info found" || (echo "✗ Version info missing" && exit 1)
          
          echo "✅ HTML validation passed!"
        else
          echo "✗ $HTML_FILE not found!"
          exit 1
        fi
      
      # Check appspec.yml
      - echo "Validating appspec.yml..."
      - |
        APPSPEC_FILE="appspec.yml" 
        
        if [ -f "$APPSPEC_FILE" ]; then
          echo "✓ $APPSPEC_FILE exists"
          
          # Validate YAML syntax
          python3 -c "import yaml; yaml.safe_load(open('$APPSPEC_FILE'))" && echo "✓ Valid YAML syntax" || (echo "✗ Invalid YAML" && exit 1)
          
          # Check for required sections
          grep -q "version:" "$APPSPEC_FILE" && echo "✓ Version specified" || (echo "✗ Version missing" && exit 1)
          grep -q "files:" "$APPSPEC_FILE" && echo "✓ Files section found" || (echo "✗ Files section missing" && exit 1)
          grep -q "hooks:" "$APPSPEC_FILE" && echo "✓ Hooks section found" || (echo "✗ Hooks section missing" && exit 1)
          
          echo "✅ appspec.yml validation passed!"
        else
          echo "✗ $APPSPEC_FILE not found!"
          exit 1
        fi
      
      # Check deployment scripts
      - echo "Validating deployment scripts..."
      - |
        SCRIPTS_DIR="app/scripts"  # ← CHANGE THIS if scripts are elsewhere
        SCRIPT_ERRORS=0
        
        if [ -f "$SCRIPTS_DIR/backup_blue.sh" ]; then
          echo "✓ backup_blue.sh exists"
          bash -n "$SCRIPTS_DIR/backup_blue.sh" && echo "  ✓ Valid bash syntax" || ((SCRIPT_ERRORS++))
        else
          echo "✗ backup_blue.sh not found"
          SCRIPT_ERRORS=$((SCRIPT_ERRORS + 1))
        fi
        
        if [ -f "$SCRIPTS_DIR/set_permissions.sh" ]; then
          echo "✓ set_permissions.sh exists"
          bash -n "$SCRIPTS_DIR/set_permissions.sh" && echo "  ✓ Valid bash syntax" || ((SCRIPT_ERRORS++))
        else
          echo "✗ set_permissions.sh not found"
          SCRIPT_ERRORS=$((SCRIPT_ERRORS + 1))
        fi
        
        if [ -f "$SCRIPTS_DIR/restart_server.sh" ]; then
          echo "✓ restart_server.sh exists"
          bash -n "$SCRIPTS_DIR/restart_server.sh" && echo "  ✓ Valid bash syntax" || ((SCRIPT_ERRORS++))
        else
          echo "✗ restart_server.sh not found"
          SCRIPT_ERRORS=$((SCRIPT_ERRORS + 1))
        fi
        
        if [ -f "$SCRIPTS_DIR/validate.sh" ]; then
          echo "✓ validate.sh exists"
          bash -n "$SCRIPTS_DIR/validate.sh" && echo "  ✓ Valid bash syntax" || ((SCRIPT_ERRORS++))
        else
          echo "✗ validate.sh not found"
          SCRIPT_ERRORS=$((SCRIPT_ERRORS + 1))
        fi
        
        if [ $SCRIPT_ERRORS -gt 0 ]; then
          echo "✗ Script validation failed with $SCRIPT_ERRORS errors"
          exit 1
        else
          echo "✅ All deployment scripts validated!"
        fi
      
      # Security checks
      - echo "Running security checks..."
      - |
        # Check for hardcoded credentials
        if grep -r -i "password\|secret\|api_key\|token" --include="*.html" --include="*.sh" --exclude="buildspec*.yml" . | grep -v "password.*meta\|secret.*meta"; then
          echo "⚠️  Warning: Potential hardcoded credentials found"
        else
          echo "✓ No hardcoded credentials detected"
        fi
      
      # Generate test report
      - echo "Generating test report..."
      - |
        cat > $TEST_RESULTS_DIR/test-report.txt << EOF
        ========================================
        Application Test Report
        ========================================
        Environment: $ENVIRONMENT
        Date: $(date)
        
        Test Results:
        ✅ HTML structure validation: PASSED
        ✅ appspec.yml validation: PASSED
        ✅ Deployment scripts validation: PASSED
        ✅ Security checks: PASSED
        ✅ File structure: PASSED
        
        Overall Status: ALL TESTS PASSED
        ========================================
        EOF
      
      - cat $TEST_RESULTS_DIR/test-report.txt
      
      - echo "✅ All tests completed successfully!"

  post_build:
    commands:
      - echo "Test phase completed"
      - echo "Creating test summary..."
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "✅ Build Status: SUCCESS"
          echo "All tests passed. Ready for deployment."
        else
          echo "❌ Build Status: FAILED"
          echo "Tests failed. Deployment blocked."
          exit 1
        fi

reports:
  test-reports:
    files:
      - 'test-results/test-report.txt'
    file-format: 'PLAIN_TEXT'

artifacts:
  files:
    - '**/*'
  name: TestOutput
