AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  TargetGroupBlue:
    Type: String

Resources:

  AlbLogBucketPrimary:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-alb-logs-primary"
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  AlbLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AlbLogBucketPrimary
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticloadbalancing.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-alb-logs-primary/*"
  
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and HTTPS from the internet to ALB
      VpcId: !Ref VpcId
  
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-alb-sg"
  
  ALBPrimary:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvironmentName}-alb"
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref AlbSecurityGroup
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: "true"
        - Key: access_logs.s3.bucket
          Value: !Ref AlbLogBucketPrimary

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBPrimary
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupBlue
  
  PrimaryALBDNSParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /dr/primary/alb/dns
      Type: String
      Value: !GetAtt ALBPrimary.DNSName

  PrimaryALBZoneParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /dr/primary/alb/zoneid
      Type: String
      Value: !GetAtt ALBPrimary.CanonicalHostedZoneID

     
Outputs:
  PrimaryALBDNS:
    Value: !GetAtt ALBPrimary.DNSName

  PrimaryALBZoneId:
    Value: !GetAtt ALBPrimary.CanonicalHostedZoneID

  PrimaryALBID:
    Value: !GetAtt ALBPrimary.LoadBalancerFullName

  Listener:
    Value: !GetAtt Listener.Arn











