AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  TargetGroupBlue:
    Type: String
  AlbSecurityGroup:
    Type: String
    
Resources:
  
  AlbLogBucketSecondary:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-alb-logs-secondary"
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
        
  AlbLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AlbLogBucketSecondary
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticloadbalancing.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-alb-logs-secondary/*"

  ALBSecondary:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvironmentName}-alb"
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref AlbSecurityGroup
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: "true"
        - Key: access_logs.s3.bucket
          Value: !Ref AlbLogBucketSecondary

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBSecondary
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupBlue
  
  SecondaryALBDNSParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /dr/secondary/alb/dns
      Type: String
      Value: !GetAtt ALBSecondary.DNSName
  
  SecondaryALBZoneParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /dr/secondary/alb/zoneid
      Type: String
      Value: !GetAtt ALBSecondary.CanonicalHostedZoneID
  

Outputs:
  SecondaryALBDNS:
    Value: !GetAtt ALBSecondary.DNSName
  
  PrimaryALBZoneId:
    Value: !GetAtt ALBSecondary.CanonicalHostedZoneID

  Listener: 
    Value: !Ref Listener

  SecondaryALBID:
    Value: !GetAtt ALBSecondary.LoadBalancerFullName

  










