AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnviromentName:
    Type: String

  GitHubOwner:
    Type: String

  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: main

  GitHubToken:
    Type: String
    NoEcho: true

  CodeDeployApplication:
    Type: String
  
  CodeDeployDeploymentGroup:
    Type: String
  
  CodepipeRoleArn:
    Type: String
    

Resources:

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Ref CodepipeRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStoreBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Deploy
          Actions:
            - Name: Codedeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: /aws/codepipeline/MultiRegionDR
      Tags:
        - Key: Name
          Value: !Sub "${EnviromentName}-Pipeline"


Outputs:
  PipelineName:
    Value: !Ref Pipeline

