AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String

Resources:

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${EnvironmentName}-tests"
      ServiceRole: !Sub "${EnvironmentName}-test-build-role"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-test.yml
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-test-project"


Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject






