version: 0.2

phases:
  post_build:
    commands:
      - echo "Creating CodeDeploy deployment group..."
      - |
        aws deploy create-deployment-group \
          --application-name dev-CodeDeployApp \
          --deployment-group-name dev-dg \
          --service-role-arn arn:aws:iam::975050225555:role/dev-CodeDeployRole \
          --deployment-style deploymentType=BLUE_GREEN,deploymentOption=WITH_TRAFFIC_CONTROL \
          --auto-scaling-groups Dev-Multi-RegionDR-Stack-East-ComputeStack-2N1P7OTCGNKT-AutoScalingGroup-rsc1T4crvqHq \
          --load-balancer-info 'targetGroupInfoList=[{name=dev-tg-blue}]' \
          --blue-green-deployment-configuration '{"terminateBlueInstancesOnDeploymentSuccess":{"action":"TERMINATE","terminationWaitTimeInMinutes":1},"deploymentReadyOption":{"actionOnTimeout":"CONTINUE_DEPLOYMENT"},"greenFleetProvisioningOption":{"action":"COPY_AUTO_SCALING_GROUP"}}' \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --region us-east-1
