AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Type: String

  InstanceAmiId:
    Type: String

  InstanceType:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  VpcId:
    Type: String

Resources:

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-app-sg"

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-InstanceRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole
      Path: /

  TargetGroupBlue:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvironmentName}-tg-blue"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port

  TargetGroupGreen:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvironmentName}-tg-green"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref InstanceAmiId
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !Ref AppSecurityGroup
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        UserData: !Base64 |
          #!/bin/bash
          set -e
          yum update -y
          yum install -y aws-cli httpd amazon-cloudwatch-agent
          yum install -y ruby
          mkdir -p /var/www/html
          echo "<h1>App Running</h1>" > /var/www/html/index.html
          systemctl enable httpd
          systemctl start httpd
          REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
          if [ -f /etc/os-release ] && grep -q "Amazon Linux" /etc/os-release; then
            wget https://aws-codedeploy-${REGION}.s3.${REGION}.amazonaws.com/latest/install -O /tmp/install
            chmod +x /tmp/install
            /tmp/install auto
          fi
          systemctl enable codedeploy-agent
          systemctl start codedeploy-agent
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
              -a fetch-config \
              -m ec2 \
              -c ssm:/CloudWatch/AgentConfig \
              -s

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      TargetGroupARNs:
        - !Ref TargetGroupBlue
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-asg"
          PropagateAtLaunch: true

Outputs:

  AutoScalingGroupName:
    Value: !Ref AutoScalingGroup
    
  AppSecurityGroup:
    Value: !Ref AppSecurityGroup

  InstanceProfileName:
    Value: !Ref InstanceProfile

  TargetGroupBlue:
    Value: !Ref TargetGroupBlue

  TargetGroupGreen:
    Value: !Ref TargetGroupGreen




