
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
    
  VpcCidr:
    Type: String
    
  PublicSubnet1Cidr:
    Type: String
    
  PublicSubnet2Cidr:
    Type: String
    
  InstanceAmiId:
    Type: String
    
  InstanceType:
    Type: String
    
  DBUsername:
    Type: String
    
  DBPassword:
    Type: String
    
  DBInstanceClass:
    Type: String
    
  AllocatedStorage:
    Type: Number
    
  Engine:
    Type: String
    
  HostedZoneName:
    Type: String
    
  HostedZoneId:
    Type: String
    
  GitHubRepo:
    Type: String
    
  GitHubOwner:
    Type: String
    
  CodeStarConnectionArn:
    Type: String  
    
  TopicName:
    Type: String
    
  EndpointEmail:
    Type: String
    
  CodepipeRoleArn:
    Type: String
    
  AlarmName:
    Type: String
    
  TargetMetricName:
    Type: String
    
 PrimaryALBDNS:
    Type: String

  PrimaryALBZoneId:
    Type: String

  SecondaryALBDNS:
    Type: String

  SecondaryALBZoneId:
    Type: String
  
Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/networkstack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SsmStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/computestack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        InstanceAmiId: !Ref InstanceAmiId
        InstanceType: !Ref InstanceType
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        VpcId: !GetAtt NetworkStack.Outputs.VpcId

  ALBStackPrimary:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/albstackprimary.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        TargetGroupBlue: !GetAtt ComputeStack.Outputs.TargetGroupBlue
        
  DatabaseStackPrimary:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/databasestackprimary.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        AllocatedStorage: !Ref AllocatedStorage
        DBInstanceClass: !Ref DBInstanceClass
        Engine: !Ref Engine

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/codedeploystack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        TargetGroupBlue: !GetAtt ComputeStack.Outputs.TargetGroupBlue
        TargetGroupGreen: !GetAtt ComputeStack.Outputs.TargetGroupGreen
        AutoScalingGroup: !GetAtt ComputeStack.Outputs.AutoScalingGroupName
        AlbListenerArn: !GetAtt ALBStackPrimary.Outputs.Listener

  CodepipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/codepipelinestack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        GitHubRepo: !Ref GitHubRepo
        GitHubOwner: !Ref GitHubOwner
        CodeStarConnectionArn: !Ref CodeStarConnectionArn
        CodepipeRoleArn: !Ref CodepipeRoleArn
        CodeDeployApplication: !GetAtt CodeDeployStack.Outputs.CodeDeployApplication
        CodeDeployDeploymentGroup: !GetAtt CodeDeployStack.Outputs.CodeDeployDeploymentGroup

  Route53Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/route53stack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        HostedZoneName: !Ref HostedZoneName
        PrimaryALBZoneId: !Ref PrimaryALBZoneId
        SecondaryALBZoneId: !Ref SecondaryALBZoneId
        PrimaryALBDNS: !Ref PrimaryALBDNS
        SecondaryALBDNS: !Ref SecondaryALBDNS

  SnsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/snsstack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        TopicName: !Ref TopicName
        EndpointEmail: !Ref EndpointEmail
        
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/monitoringstack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AlarmName: !Ref AlarmName
        TargetMetricName: !Ref TargetMetricName
        SNSAlertArn: !GetAtt SnsStack.Outputs.SNSTopic
        PrimaryALBID: !GetAtt ALBStackPrimary.Outputs.PrimaryALBDID

  PrimaryBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/primarybucketstack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  SsmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ssmstack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
 

        













