AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvironmentName:
    Type: String

Resources:
  SecondaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-secondary-dr-bucket-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-secondary-dr-bucket"

Outputs:
  SecondaryBucketName:
    Value: !Ref SecondaryBucket
  SecondaryBucketArn:
    Value: !GetAtt SecondaryBucket.Arn
