AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  EnviromentName:
    Type: String

  TopicName:
    Type: String
    
  EndpointEmail:
    Type: String


Resources:
  DAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      Tags:
        - Key: Name
          Value: !Sub "${EnviromentName}-DAlertTopic"
      
    
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EndpointEmail
      Protocol: email
      TopicArn: !Ref DAlertTopic
      Tags:
        - Key: Name
          Value: !Sub "${EnviromentName}-EmailSubscription"


Outputs:
  SNSTopic:
    Value: !GetAtt DAlertTopic.Arn
  
  SNSEmailSubscription:
    Value: !Ref EmailSubscription
