AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  EnvironmentName:
    Type: String

  TopicName:
    Type: String
    
  EndpointEmail:
    Type: String


Resources:
  DAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-DAlertTopic"
      
    
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EndpointEmail
      Protocol: email
      TopicArn: !Ref DAlertTopic


Outputs:
  SNSTopic:
    Value: !Ref DAlertTopic
  
  SNSEmailSubscription:
    Value: !Ref EmailSubscription
